name = "mini-mod"
license = "MIT"
licenselink = "https://github.com/billywba/mini-mod/blob/master/LICENSE.md"
description = "A fast, minimalist and responsive hugo theme for bloggers."
homepage = "https://github.com/billywba/mini-mod/"
tags = ["blog", "fast", "minimalist", "responsive", "simple", "beautiful", "tags", "pages"]
features = ["fast", "minimalist", "responsive", "archive", "tags"]
min_version = "0.134.1"

[author]
    name = "billywba"
    homepage = "https://github.com/billywba"

[original]
    name = "nodejh"
    homepage = "https://github.com/nodejh"
    repo = "https://github.com/nodejh/hugo-theme-mini"