baseURL: https://github.com/billywba/mini-mod
languageCode: en-us
title: Hugo
theme: hugo-theme-mini
paginate: 3

# !!! exampleSite only, you may need to delete the line: `themesDir: ../../` 
themesDir: ../../

hasCJKLanguage: true
permalinks:
  posts: /posts/:title/

googleAnalytics: UA-123-45
disqusShortname: billywba


markup:
  highlight:
    guessSyntax: true
    style: emacs


social:
  github: https://github.com/billywba


params:
  author: billywba
  bio: Software Engineer
  description: My Blog
  enableRSS: true
  enableComments: true
  enableGoogleAnalytics: true
