baseURL = "https://example.com"
languageCode = "en-us"
title = "Hugo"
theme = "mini-mod"


[params]
author = "Author"
bio = "Software Engineer"
description = "My blog"

# Optional params

# To enable RSS, set `enableRSS = true`, default is `true`
enableRSS = true

# To enable comments, you may need to set `disqusShortname`
enableComments = true
# disqusShortname =  "your-disqus-shortname"

# To enable comments, you may need to set `googleAnalytics`
enableGoogleAnalytics = true
# googleAnalytics = "your-google-analytics-id"

# To enable table of content, set `showToc = true`, default is `false`
showToc = true

# To hidde powerBy message in the page footer, set `showPowerBy = false`, default is `true`
showPowerBy = true

# To enable math typesetting, set `math = true`, default is `false`
math = false

# To hide post summary in home page, set `hiddenPostSummaryInHomePage = true`, default is `false`
hiddenPostSummaryInHomePage = false

# Website copyright, default: '© Copyright 2021 ❤️ {params.author}'
copyright = ""

# Custom CSS example
# customCSS = [
# "https://example.com/styles/remote.css",  # Remote CSS
# "css/local-style.css"                     # Local CSS
# ]

# Custom JS example
# customJS = [
#   "https://example.com/scripts/remote.js",  # Remote JS
#   "js/local-script.js"                      # Local JS
# ]

# Social links in footer, supports: github, twitter, stackoverflow and facebook
[params.social]
github = "https://www.github.com/billywba"
twitter = "https://www.twitter.com/billy_wbaa"
stackoverflow = ""

# Add new links
[[params.Links]]
name = "Project"
path = "/project"

# Add another link
# [[params.Links]]
#   name = "Test"
#   path = "/test"

[pagination]
pagerSize = 10